### ISSUE TITLE
Feedback for Consume VMware VMs on Azure

### ISSUE THREAD

**Issue by wolruf** [CloudSimpleDocs/docsfeedback#3]
Issue in http://docs.azure.cloudsimple.com/quickstart-create-vmware-virtual-machine/

Links at the bottom of page are 404:
https://docs.azure.cloudsimple.com/azurelistvms
https://docs.azure.cloudsimple.com/azureoverviewpage

**Comment by sharaths-cs** [comment]
Thank you for reporting the issue.  We have fixed and updated the article.
